# Generated by Django 5.1.4 on 2024-12-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="username",
            field=models.CharField(default="defaultUsername", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="submission",
            name="score",
            field=models.JSONField(),
        ),
    ]
